workflows:
  testing-workflow:
    name: iOS Workflow
    environment:
      vars:
        XCODE_WORKSPACE: "TVToday.xcworkspace"
        XCODE_SCHEME: "TVToday"
      xcode: latest
      cocoapods: default
    triggering:
      branch_patterns:
        - pattern: "master"
          include: true
          source: true
    scripts:
      - name: Installing tuist
        script: curl -Ls https://install.tuist.io | bash
      - name: Generate project
        script: tuist generate
      - name: Run tests
        script: tuist test
        test_report: build/ios/test/*.xml
