workflows:
  testing-workflow:
    name: iOS Workflow
    instance_type: mac_pro
    environment:
      vars:
        XCODE_WORKSPACE: "TVToday.xcworkspace"
        XCODE_SCHEME: "TVToday"
      xcode: latest
      cocoapods: default
    triggering:
      events: 
        - push
    scripts:
      - name: Installing tuist
        script: curl -Ls https://install.tuist.io | bash
      - name: Generate project
        script: tuist generate
      - name: Run tests
        script: tuist test
        test_report: build/ios/test/*.xml
  testing-m1-workflow:
    name: iOS M1 Workflow
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "TVToday.xcworkspace"
        XCODE_SCHEME: "TVToday"
      xcode: latest
      cocoapods: default
    triggering:
      events: 
        - push
    scripts:
      - name: Installing tuist
        script: curl -Ls https://install.tuist.io | bash
      - name: Generate project
        script: tuist generate
      - name: Run tests
        script: arch -arm64 tuist test
        test_report: build/ios/test/*.xml
